collections:
# ibm.isam (name only)
- name: ibm.isam
# Custom collection, for example from an internal git repo
- name: custom.isam
  version: dev
  type: git
  source: 'https://github.com/tombosmansibm/custom_isam_collection.git'