collections:
# ibm.isam (name only)
  - name: ibm.isam
# problem with a hostname is that it won't resolve .... 
  - name: custom.isam
    source: 'http://9.171.16.83:8000'
 #This does not work on Tower:
 # - name: 'git@github.com:tombosmansibm/custom_isam_collection.git'
 #   version: dev
 #   type: git
#   source: 'git@github.com:tombosmansibm/custom_isam_collection.git'
# Custom collection, for example from an internal git repo
#- name: custom.isam
#  version: dev
#  type: git
#  source: 'https://github.com/tombosmansibm/custom_isam_collection.git'
