collections:
# ibm.isam (name only)
  - name: ibm.isam
  - name: git@github.com:tombosmansibm/custom_isam_collection.git
    version: dev
    type: git
    source: 'git@github.com:tombosmansibm/custom_isam_collection.git'
# Custom collection, for example from an internal git repo
#- name: custom.isam
#  version: dev
#  type: git
#  source: 'https://github.com/tombosmansibm/custom_isam_collection.git'
