---
# main task to get timezones
- name: Help INFO (-e help=true)
  pause:
    echo: yes
    prompt: |
      NAME
        get_timezones

      DESCRIPTION
        Role to retrieve timezones with a custom package

      STEPS
        1) get timezones

      EXAMPLES
        ansible-playbook -i [...] p

      ==========

      INTERACTION
        ENTER         = continue
        Ctrl+C + 'C'  = continue
        Ctrl+C + 'A'  = abort
  when: help is defined

- name: Retrieve a bogus list of timezones
  isam:
    log: "{{ log_level | default(omit) }}"
    force: "{{ force | default(omit) }}"
    action: tbosmans.isam.base.date_time.get_timezones
    isamapi: 
  register: timezones_obj

- name: debug
  debug:
     msg: "{{ timezones_obj.data|default('') | to_nice_yaml }}"