---
# Base Setup
#   This playbook shows how to reference your own custom collection, while stil using the "ibm.isam" namespace.
#
#   Please note that this playbook does require an inventory.
#
#   Example:
#      iterator:
- hosts: "all"
  gather_facts: no
  collections:
    - custom.isam
  tasks:
    - name: Perform First Steps
      tags: ["first", "steps"]
      include_role:
        name: ibm.isam.base.first_steps
      vars:
        first_steps_admin_pwd: True
#
# This is a role without FQCN
#   It will first look in this collection and then in the ibm.isam collection
#
    - name: Configure NTP
      tags: ["ntp"]
      include_role:
       name: base.configure_time
#
# This uses a role from the "custom.isam" collection, that does not exist in ibm.isam
#
    - name: Show configured static routes
      tags: ["ipv4"]
      include_role:
        name: custom.isam.base.get_static_routes

